version: "3.1"

services:
  jwt:
    build:
      context: .
      dockerfile: ./app.Dockerfile
    container_name: jwt
    restart: always
    ports:
      - 3000:3000
    environment:
      - PORT=${PORT}
      - HOST=${HOST}