version: "3.1"

services:
  jwt:
    build:
      context: .
      dockerfile: ./app.Dockerfile
    container_name: jwt
    restart: always
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      - APP_PORT
      - APP_HOST
    networks:
      app-net: {}
    volumes:
      - ./keys:/app/keys

networks:
  app-net:
    external: true
    name: "gramwannabe-net"
